workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^features\// && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == null'
      when: never

    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

    - when: never

default:
  tags:
    - my-runner

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: myreg.example.ir

build_vote:
  stage: build
  script:
    - docker build -t $REGISTRY/vote:v1 ./vote
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - vote/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - vote/**/*
      when: always
    - when: never

build_result:
  stage: build
  script:
    - docker build -t $REGISTRY/result:v1 ./result
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - result/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - result/**/*
      when: always
    - when: never

build_worker:
  stage: build
  script:
    - docker build -t $REGISTRY/worker:v1 ./worker
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - worker/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - worker/**/*
      when: always
    - when: never

push_vote:
  stage: push
  before_script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY -u "$NEXUS_USER" --password-stdin
  script:
    - docker push $REGISTRY/vote:v1
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - vote/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - vote/**/*
      when: always
    - when: never

push_result:
  stage: push
  before_script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY -u "$NEXUS_USER" --password-stdin
  script:
    - docker push $REGISTRY/result:v1
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - result/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - result/**/*
      when: always
    - when: never

push_worker:
  stage: push
  before_script:
    - echo "$NEXUS_PASSWORD" | docker login $REGISTRY -u "$NEXUS_USER" --password-stdin
  script:
    - docker push $REGISTRY/worker:v1
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - worker/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - worker/**/*
      when: always
    - when: never
